support for Ubuntu 20.04
voxpupuli/puppet-letsencrypt pull request #244
Opened 2021-04-27 18:53 UTC by lschierer

#### Pull Request (PR) description
When I added a Ubuntu 20.04 node to my puppet master, it could not find the package name for the DNS plugin.  This fixed it. 

#### This Pull Request (PR) fixes the following issues

2021-04-27 20:28 UTC, kenyon commented
We would also need to update metadata.json to declare support for Ubuntu 20.04.

2021-04-27 20:33 UTC, lschierer commented
I have updated that file now as well, I missed it before.

2021-04-27 20:33 UTC, kenyon requested changes

2021-04-27 20:33 UTC, kenyon commented on metadata.json
>          "18.04"
```suggestion
        "18.04",
```

2021-04-27 21:16 UTC, lschierer commented on metadata.json
>          "18.04"
done

2021-04-27 23:35 UTC, kenyon reviewed
Thanks. Looks like the remaining work to get the tests to pass is in #235 and possibly other PRs.

2021-04-28 01:44 UTC, lschierer commented
can we remove the needs work label, or is there more I should do?

2021-06-30 14:01 UTC, lschierer commented
it looks like a maintainer has to approve the workflow now to see if the latest merge from upstream resolves any of the test failures.

2021-06-30 14:11 UTC, lschierer commented
it appears I am now passing all checks, so the tests-fail tag added by https://github.com/voxpupuli/puppet-letsencrypt/pull/244#issuecomment-858544263 should be removed.

2021-06-30 14:40 UTC, ekohl approved these changes

2021-06-30 15:12 UTC, ekohl commented
@kenyon I think your concerns have been addressed, but you are listed as "requested changes" now. Any objections to merging this?

Also, we should squash this. We can do that while merging, but IMHO it's better for a cleaner git log.

2021-06-30 15:22 UTC, lschierer commented
now squashed per request.

2021-06-30 15:25 UTC, ekohl commented
Looks like something went wrong there because I see 18 commits. Can you use `git rebase`?

2021-06-30 15:44 UTC, lschierer commented
I cannot figure out enough git rebase to clean this up. I'm going to close this and recreate it.

2021-06-30 15:44 UTC, closed without merging